// <auto-generated />
using ChekaneCRM.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChekaneCRM.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506211150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChekaneCRM.Backend.Models.Database.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Булочки",
                            Description = "Слоеный с маслом",
                            IsAvailable = true,
                            Name = "Круассан",
                            Price = 120m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Хлеб",
                            Description = "Хрустящий французский",
                            IsAvailable = true,
                            Name = "Багет",
                            Price = 80m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Торты",
                            Description = "Нежный медовый торт",
                            IsAvailable = true,
                            Name = "Медовик",
                            Price = 450m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
